apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application
  labels:
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: snaket2628/todo-app:latest
        ports:
        - containerPort: 3000
